# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  postgres-service:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - spring-boot-postgres-network
    restart: always
    volumes:
      - ./db/postgres/ddl/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=skyline
      - POSTGRES_PASSWORD=skyline
      - POSTGRES_DB=skylinedb
      - TZ=America/Sao_Paulo
  api-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - spring-boot-postgres-network
    volumes:
      - ./:/logs
    depends_on:
      - postgres-service
networks:
  spring-boot-postgres-network:
    driver: bridge
