# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  mysql-service:
    image: mysql:5.6
    ports:
      - "3306:3306"
    networks:
      - spring-boot-mysql-network
    restart: always
    volumes:
      - ./db/mysql/ddl/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=skyline
      - MYSQL_USER=skyline
      - MYSQL_PASSWORD=skyline
      - MYSQL_DATABASE=skylinedb
  api-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge